

services:
  laravel.test:
    build:
      context: ./geriatrico/vendor/laravel/sail/runtimes/8.4
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.4/app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE}'
      XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG}'
      IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - './geriatrico:/var/www/html'
    networks:
      - sail
    depends_on:
      - mysql

  react:
    build:
      context: ./frontGeriatrico
      dockerfile: Dockerfile # asegurate de tener un Dockerfile simple para React
    container_name: laraveldocker-react
    ports:
      - '3000:3000'
    volumes:
      - './frontGeriatrico:/app'
      - '/app/node_modules'
    networks:
      - sail
    depends_on:
      - laravel.test

  mysql:
    image: 'mysql:8.0'
    container_name: laraveldocker-mysql
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - 'sail-mysql:/var/lib/mysql'
    networks:
      - sail
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 10s
    command: --default-authentication-plugin=mysql_native_password

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
